version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "wednesday"
      time: "23:30"
    open-pull-requests-limit: 5
    ignore:
      - dependency-name: "fastapi"
        versions: ["<0.91.0"]
