apiVersion: v1
kind: Service
metadata:
  name: app-service
  namespace: prod
  labels:
    app: my-app
spec:
  selector:
    app: my-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: ClusterIP
