apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: require-resource-limits
spec:
  validationFailureAction: enforce
  rules:
    - name: require-resource-limits
      match:
        resources:
          kinds:
            - Pod
            - Deployment
            - StatefulSet
            - ReplicaSet
      namespaceSelector:
        matchNames:
          - prod
          - dev
      validate:
        message: "Resource limits must be set for CPU and memory in the 'prod' and 'dev' namespaces."
        pattern:
          spec:
            containers:
              - resources:
                  limits:
                    cpu: "?*" 
                    memory: "?*"  
        deny:
          conditions:
            - key: "{{request.object.spec.containers[0].resources.limits.cpu}}"
              operator: GreaterThan
              value: "2" 
            - key: "{{request.object.spec.containers[0].resources.limits.memory}}"
              operator: GreaterThan
              value: "1Gi" 